### PR TITLE
add my part Bao

### PR DESCRIPTION
**Pull request by baovu98**

### CODE REVIEW

**Comment by TaranChowdhury** [comment]
missing titles for the use cases check pleae

**Review by TaranChowdhury — CHANGES_REQUESTED** [review]
get rid of the hashes i.e. "##" and also include use case titles. delete the excessive spaces in between lines

all you have to do is cancel your current request, modify the file, commit, and push again

**Comment by tnguyenswe** [comment]
we actually need to be formatting it with the hashes- we all need to change it to this format

**Review by tnguyenswe — APPROVED** [review]
ok

**Pull request merged**
